package com.github.kotlintubeexplode.integration

import com.github.kotlintubeexplode.client.YoutubeClient
import com.github.kotlintubeexplode.testdata.VideoIds
import io.kotest.matchers.ints.shouldBeGreaterThanOrEqual
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import kotlin.time.Duration.Companion.seconds

/**
 * Integration tests for closed-caption extraction against live YouTube.
 *
 * Test cases derived from upstream's ClosedCaptionSpecs.cs.
 *
 * Coverage gap: track-fetch and individual-caption tests from upstream are
 * not included here. The /api/timedtext endpoint currently returns HTTP 200
 * with an empty body for our requests (signed URLs from the manifest do
 * authenticate, but the response is empty). Likely the same auth drift that
 * broke stream extraction earlier (PO-token-style requirement). Tracked as
 * KNOWN_DRIFT.md item #16.
 */
@Tag("integration")
@DisplayName("Closed Caption Integration Tests")
class ClosedCaptionIntegrationTest {

    private val client = YoutubeClient()

    @Nested
    @DisplayName("Manifest")
    inner class ManifestTests {
        // Mirror of upstream's I_can_get_the_list_of_available_closed_caption_tracks_on_a_video.

        @Test
        fun `should list multiple caption tracks for a video with captions`() = runTest(timeout = 60.seconds) {
            val manifest = client.closedCaptions.getManifest(VideoIds.WithClosedCaptions)

            manifest.tracks.size shouldBeGreaterThanOrEqual 3

            // Auto-generated English track present.
            assert(manifest.tracks.any { it.language.code == "en" && it.isAutoGenerated }) {
                "Expected an auto-generated en track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }

            // Manual en-US track present.
            assert(manifest.tracks.any { it.language.code == "en-US" && !it.isAutoGenerated }) {
                "Expected a manual en-US track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }

            // Manual es-419 track present.
            assert(manifest.tracks.any { it.language.code == "es-419" && !it.isAutoGenerated }) {
                "Expected a manual es-419 track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }
        }
    }
}
