package com.github.kotlintubeexplode.integration

import com.github.kotlintubeexplode.client.YoutubeClient
import com.github.kotlintubeexplode.testdata.VideoIds
import io.kotest.matchers.collections.shouldNotBeEmpty
import io.kotest.matchers.ints.shouldBeGreaterThanOrEqual
import io.kotest.matchers.string.shouldNotBeBlank
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import kotlin.time.Duration.Companion.seconds

/**
 * Integration tests for closed-caption extraction against live YouTube.
 *
 * Test cases derived from upstream's ClosedCaptionSpecs.cs.
 *
 * Covers both the manifest (available tracks) and a track fetch (the captions themselves).
 * The track fetch exercises the #16 path: caption baseUrls come from the ANDROID_VR client,
 * which serves real timedtext — the WEB baseUrls returned HTTP 200 with an empty body.
 */
@Tag("integration")
@DisplayName("Closed Caption Integration Tests")
class ClosedCaptionIntegrationTest {

    private val client = YoutubeClient()

    @Nested
    @DisplayName("Manifest")
    inner class ManifestTests {
        // Mirror of upstream's I_can_get_the_list_of_available_closed_caption_tracks_on_a_video.

        @Test
        fun `should list multiple caption tracks for a video with captions`() = runTest(timeout = 60.seconds) {
            val manifest = client.closedCaptions.getManifest(VideoIds.WithClosedCaptions)

            manifest.tracks.size shouldBeGreaterThanOrEqual 3

            // Auto-generated English track present.
            assert(manifest.tracks.any { it.language.code == "en" && it.isAutoGenerated }) {
                "Expected an auto-generated en track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }

            // Manual en-US track present.
            assert(manifest.tracks.any { it.language.code == "en-US" && !it.isAutoGenerated }) {
                "Expected a manual en-US track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }

            // Manual es-419 track present.
            assert(manifest.tracks.any { it.language.code == "es-419" && !it.isAutoGenerated }) {
                "Expected a manual es-419 track. Got: ${manifest.tracks.map { it.language.code to it.isAutoGenerated }}"
            }
        }
    }

    @Nested
    @DisplayName("Track")
    inner class TrackTests {
        // Mirror of upstream's ClosedCaptionSpecs track-fetch test. Validates the #16 fix:
        // ANDROID_VR-sourced caption baseUrls return real timedtext (the WEB baseUrls returned
        // HTTP 200 with an empty body). Uses the manual en-US track: manual tracks reliably
        // carry offset+duration, so their captions survive get()'s null-offset/duration filter.

        @Test
        fun `should fetch a caption track and return captions carrying text`() = runTest(timeout = 60.seconds) {
            val manifest = client.closedCaptions.getManifest(VideoIds.WithClosedCaptions)
            val trackInfo = manifest.getByLanguage("en-US")

            val track = client.closedCaptions.get(trackInfo)

            track.captions.shouldNotBeEmpty()
            track.captions.forEach { it.text.shouldNotBeBlank() }
        }
    }
}
