package com.github.kotlintubeexplode.videos.closedcaptions

import com.github.kotlintubeexplode.common.Language

/**
 * Metadata associated with a closed caption track of a YouTube video.
 *
 * @param url Track URL for fetching the captions
 * @param language Track language
 * @param isAutoGenerated Whether the track was automatically generated by YouTube
 */
data class ClosedCaptionTrackInfo(
    val url: String,
    val language: Language,
    val isAutoGenerated: Boolean
) {
    override fun toString(): String = "CC Track (${language})"
}
