package com.github.kotlintubeexplode.videos.closedcaptions

/**
 * Describes closed caption tracks available for a YouTube video.
 *
 * @param tracks Available closed caption tracks
 */
data class ClosedCaptionManifest(
    val tracks: List<ClosedCaptionTrackInfo>
) {
    /**
     * Gets the closed caption track in the specified language.
     * The language can be identified by ISO-639-1 code or display name.
     *
     * @param language The language code (e.g., "en") or name (e.g., "English")
     * @return The matching track, or null if not found
     */
    fun tryGetByLanguage(language: String): ClosedCaptionTrackInfo? =
        tracks.firstOrNull { track ->
            track.language.code.equals(language, ignoreCase = true) ||
            track.language.name.equals(language, ignoreCase = true)
        }

    /**
     * Gets the closed caption track in the specified language.
     * The language can be identified by ISO-639-1 code or display name.
     *
     * @param language The language code (e.g., "en") or name (e.g., "English")
     * @return The matching track
     * @throws NoSuchElementException if no track is found for the specified language
     */
    fun getByLanguage(language: String): ClosedCaptionTrackInfo =
        tryGetByLanguage(language)
            ?: throw NoSuchElementException("No closed caption track available for language '$language'")

    /**
     * Returns the number of available tracks.
     */
    val size: Int get() = tracks.size

    /**
     * Returns true if no caption tracks are available.
     */
    val isEmpty: Boolean get() = tracks.isEmpty()

    /**
     * Gets all auto-generated caption tracks.
     */
    fun getAutoGeneratedTracks(): List<ClosedCaptionTrackInfo> =
        tracks.filter { it.isAutoGenerated }

    /**
     * Gets all manually created (non-auto-generated) caption tracks.
     */
    fun getManualTracks(): List<ClosedCaptionTrackInfo> =
        tracks.filter { !it.isAutoGenerated }
}
